name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Surge
      run: npm install --global surge

    - name: Validate Surge Token
      run: surge token
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

    - name: Deploy to Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: surge --project ./ --majestic-ladybug.surge.sh

